### ISSUE TITLE
TileEntity error

### ISSUE THREAD

**Issue by theMusicalGamer** [theMusicalGamer/skywardSwordMod#3]
Error with TileEntityGoddessWall after I tried placing a billion of Goddess Walls everywhere

[21:33:49] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:198) ~[NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.RuntimeException: class zelda.ss.tileentity.TileEntityGoddessWall is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:96) ~[TileEntity.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:52) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:81) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:107) ~[BlockSnapshot.class:?]
	at net.minecraft.world.World.setBlock(World.java:515) ~[World.class:?]
	at net.minecraft.world.World.setBlock(World.java:681) ~[World.class:?]
	at zelda.ss.item.ItemGoddessWall.onItemUse(ItemGoddessWall.java:27) ~[ItemGoddessWall.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:507) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.tryPlaceItemIntoWorld(ItemStack.java:142) ~[ItemStack.class:?]
	at net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem(ItemInWorldManager.java:422) ~[ItemInWorldManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:593) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:74) ~[C08PacketPlayerBlockPlacement.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:122) ~[C08PacketPlayerBlockPlacement.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) ~[NetworkSystem.class:?]
	... 5 more

**Comment by theMusicalGamer** [comment]
Posted this problem to the Minecraft Forge forum.

**Comment by theMusicalGamer** [comment]
Ernio says: Did you register your TE?

**Comment by theMusicalGamer** [comment]
theMusicalGamer says: No I didn't. That's most likely the problem. I'll try that now.

**Comment by theMusicalGamer** [comment]
Fixed Issue #3: TileEntity Error
Added "GameRegistry.registerTileEntity(TileEntityGoddessWall.class, "goddessWallTE");" to SkywardSword.java
